name: QuidditchPlugin
version: '${project.version}'
main: me.pacenstein.quidditch.QuidditchPlugin
api-version: '1.20'
depend: [WorldGuard]
commands:
  jointeam:
    description: Join a team.
    usage: "/jointeam <team>"
  leaveteam:
    description: Leave your current team.
    usage: "/leaveteam"
  chooseclass:
    description: Choose your Quidditch class.
    usage: "/chooseclass <class>"
  spawnSnitch: # Add this
    description: Spawn the Snitch.
    usage: "/spawnsnitch"
  spawnquaffle:
    description: Spawns a Quaffle at the player's location.
    usage: "/spawnquaffle"
  spawnbludger:
    description: Spawns a Bludger at the player's location.
    usage: "/spawnbludger"
  clearclass:
    description: Clear your current Quidditch role.
    usage: "/clearclass"
  startgame:
    description: Start a Quidditch game.
    usage: "/startgame"
  endgame:
    description: End the current Quidditch game.
    usage: "/endgame"
  joinquidditch:
    description: Join a Quidditch game.
    usage: /joinquidditch